function [fitresult, gof] = createFit1(a, temp)
%CREATEFIT1(A,TEMP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : a
%      Y Output: temp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Jun-2015 12:28:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( a, temp );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'temp vs. a', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'a' );
ylabel( 'temp' );
grid on


