function createimage(cdata1, Parent1)
%CREATEIMAGE(CDATA1,PARENT1)
%  CDATA1:  image cdata
%  PARENT1:  image parent

%  Auto-generated by MATLAB on 26-May-2015 15:23:44

% Create image
image(cdata1,'Parent',Parent1,'CDataMapping','scaled');

